# Generated by Django 4.2.3 on 2023-07-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("username", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
