# Generated by Django 3.2.13 on 2023-08-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('lecturers', '0002_alter_lecturer_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturercourse',
            unique_together={('lecturer',)},
        ),
    ]
