# Generated by Django 3.2.13 on 2023-08-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('lecturers', '0003_alter_lecturercourse_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturercourse',
            name='course',
        ),
        migrations.AddField(
            model_name='lecturercourse',
            name='courses',
            field=models.ManyToManyField(related_name='lecturer', to='courses.Course'),
        ),
    ]
