# Generated by Django 3.2.13 on 2023-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("lecturers", "0005_auto_20230903_1045"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturercourse",
            name="program",
        ),
        migrations.AddField(
            model_name="lecturercourse",
            name="course",
            field=models.ManyToManyField(related_name="lecturer", to="courses.Course"),
        ),
    ]
