# Generated by Django 3.2.13 on 2023-09-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0006_auto_20230903_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturercourse',
            old_name='course',
            new_name='courses',
        ),
    ]
