# Generated by Django 3.2.13 on 2023-09-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0001_initial"),
        ("intakes", "0003_auto_20230903_1023"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intakeprogram",
            name="course",
        ),
        migrations.AddField(
            model_name="intakeprogram",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.program",
            ),
            preserve_default=False,
        ),
    ]
