# Generated by Django 3.2.13 on 2023-09-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0004_auto_20230903_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntakeProgram',
        ),
    ]
