# Generated by Django 4.2.6 on 2023-11-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="structures", to="courses.course"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.program",
                    ),
                ),
            ],
        ),
    ]
