# Generated by Django 4.2.6 on 2023-11-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0003_programstructure_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programstructure",
            name="enrollment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="programstructure",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.program",
            ),
        ),
    ]
