# Generated by Django 3.2.13 on 2023-08-18 04:25

from django.db import migrations
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_title'),
        ('programs', '0002_alter_program_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='program',
            name='courses',
            field=select2.fields.ManyToManyField(help_text=None, sort_value_field_name='position', to='courses.Course'),
        ),
    ]
