# Generated by Django 4.2.3 on 2023-07-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
        ("programs", "0002_auto_20230726_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.department",
            ),
            preserve_default=False,
        ),
    ]
