# Generated by Django 3.2.13 on 2023-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_title'),
        ('programs', '0003_auto_20230818_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='courses',
            field=models.ManyToManyField(related_name='programs', to='courses.Course'),
        ),
    ]
