# Generated by Django 4.2.6 on 2023-10-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
