# Generated by Django 4.2.6 on 2023-11-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lecturers", "0001_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollments",
                    models.ManyToManyField(
                        related_name="enrollment", to="programs.enrollment"
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecturers.lecturer",
                    ),
                ),
            ],
        ),
    ]
